server:
  port: ${PORT}
  ssl:
    enabled: ${SSL_ENABLED}
    key-store-type: PKCS12
    key-store: classpath:keystore/${SSL_KEY_STORE_NAME}.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    key-alias: ${SSL_KEY_ALIAS}

logging:
  level:
    org.springframework.web.client.RestTemplate: ${LOG_LEVEL}

spring:
  security:
    oauth2:
      client:
        registration:
          dis:
            client-id: ${DIS_CLIENT_ID}
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            scope:
              - openid
            redirect-uri : ${REDIRECT_URI}
        provider:
          dis:
            issuer-uri: ${DIS_ISSUER_URI}

jwk:
  keypair: ${JWK_KEYPAIR}
